CONTAINER_PORT: 8080
ACTIVE_PROFILE: prod

MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: sj07hardwarestore
MYSQL_USERNAME: austine # sj07admin
MYSQL_PASSWORD: lmk9a3dc # sj07!!admin

EMAIL_HOST: ""
EMAIL_PORT: ""
EMAIL_ID: ""
EMAIL_PASSWORD: ""

VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}
UI_API_URL: http://localhost:4200

JWT_SECRET: "VERY STRONG SECRET"
JWT_EXPIRATION: 432_000_000